modLoader="javafml"
loaderVersion="${forge_loader_requirement}"
license="Egg Producción License (All rights reserved)."
issueTrackerURL="https://github.com/henkelmax/simple-voice-chat/issues"
displayURL="https://modrepo.de/minecraft/voicechat/overview"
logoFile="icon.png"
credits="Credits to Simple Voice Chat (Max Henkel)"
authors="Egg Producción (Original by Max Henkel)"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="WDP_VOICE_EGG"
updateJSONURL="https://maxhenkel.de/update/voicechat.json"
displayTest="NONE"
description='''Chat de voz por proximidad personalizado para Egg Producción WDP.'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_requirement}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.20.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="cloth_config"
    mandatory=false
    versionRange="[${cloth_config_version},)"
    ordering="AFTER"
    side="BOTH"